const PUPPY_NAMES_DATA = {
  "male": {
    "golden_retriever": {
      "playful": [
["Biscuit","golden playful pup"],["Sunny","sunshine golden boy"],["Marley","bob marley vibes"],["Cooper","friendly cooper"],["Tucker","tuckered from play"],
["Charlie","charming charlie"],["Milo","milo the playful"],["Otis","playful otis"],["Teddy","teddy the playful"],["Bailey","bailey the playful"],
["Riley","riley the playful"],["Henry","henry the playful"],["Oliver","oliver the playful"],["Archie","archie the playful"],["Dexter","dex the playful"],
["Finn","finn the playful"],["Louie","louie the playful"],["Gus","gus the playful"],["Ziggy","ziggy the playful"],["Cody","cody the playful"],
["Toby","toby the playful"],["Rex","rex the playful"],["Benny","benny the playful"],["Jasper","jasper the playful"],["Loki","loki the playful"],
["Bentley","bentley the playful"],["Leo","leo the playful"],["Hank","hank the playful"],["Caramel","caramel-coated pup"],["Tanner","golden tanner"],
["Sandy","sandy the playful"],["Butters","butterscotch boy"],["Amber","amber the playful"],["Honey","honey the playful"],["Blaze","golden blaze"],
["Skipper","skipping pup"],["Augie","august golden"],["Juno","juno the playful"],["Brooks","brookside pup"],["Clyde","clyde the playful"],
["Angus","scottish angus"],["Brio","brio the playful"],["Bounce","bouncy golden"],["Flicker","flickering playful"],["Rolly","rolly polly pup"],
["Dune","dune the playful"],["Wally","wally the playful"],["Tater","tater the playful"],["Nugget","golden nugget"],["Bingo","bingo the playful"]
],
      "energetic": [
["Blaze","fiery golden"],["Dakota","dakota the runner"],["Ranger","ranger energy"],["Trek","trekking golden"],["Chase","chase the retriever"],
["Dash","dash the retriever"],["Canyon","canyon the runner"],["Rio","rio energy"],["Sprint","sprinting retriever"],["Maverick","maverick energy"],
["Bolt","bolt speed"],["Flash","flash the retriever"],["Storm","stormy retriever"],["Comet","comet the runner"],["Rocket","rocket energy"],
["Arrow","arrow the retriever"],["Hawk","hawk-eyed hunter"],["Strider","long strider"],["Gallop","galloping golden"],["River","river runner"],
["Rush","rushing energy"],["Titan","titanic golden"],["Trekker","trekking retriever"],["Phoenix","phoenix rising"],["Rebel","rebel runner"],
["Jet","jet speed"],["Thor","thunder energy"],["Brisk","brisk pace"],["Dune","dune runner"],["Clyde","clyde energy"],
["Boomer","boomer energy"],["Bandit","bandit runner"],["Vortex","vortex energy"],["Cyclone","cyclone energy"],["Dynamo","dynamo power"],
["Spark","spark energy"],["Surge","surge energy"],["Fury","fury energy"],["Flash","flash speed"],["Stride","strider energy"],
["Charger","charger energy"],["Wild","wild energy"],["Zest","zesty runner"],["Comet","comet speed"],["Maverick","maverick speed"],
["Marathon","marathon runner"],["Cascade","cascade energy"],["Glen","glen runner"],["Boulder","boulder strength"],["Summit","summit reacher"],
["Pioneer","pioneer runner"],["Viking","viking runner"],["Mariner","mariner explorer"],["Skipper","skipper retriever"]
],
      "cuddly": [
["Bear","big cuddly bear"],["Teddy","teddy bear cuddle"],["Milo","sweet cuddle bug"],["Ollie","cuddly ollie"],["Charlie","charming cuddle"],
["Sammy","sweet cuddles"],["Benny","benny cuddles"],["Cubby","cubby cuddle"],["Muffin","sweet muffin"],["Pebble","pebble cuddle"],
["Sunny","sunny cuddles"],["Lucky","lucky cuddle"],["Leo","lion cuddle"],["Coby","coby cuddles"],["Archie","archie cuddle"],
["Cooper","cooper cuddles"],["Gus","gus cuddles"],["Louie","louie cuddles"],["Theo","theo cuddles"],["Woody","woody cuddles"],
["Bean","bean cuddle"],["Biscuit","biscuit cuddle"],["Bonbon","sweet bonbon"],["Bubba","bubba cuddles"],["Clover","clover cuddle"],
["Dino","dino cuddles"],["Dotty","dotty cuddles"],["Fluff","fluffy cuddle"],["Fudge","fudge sweet"],["Honey","honey sweet"],
["Jaxie","jaxie cuddles"],["Juno","juno cuddles"],["Mochi","sweet mochi"],["Nibs","nibs sweet"],["Nutty","nutty sweet"],
["Peanut","peanut sweet"],["Puff","puffy cuddle"],["Roo","roo cuddle"],["Snoopy","snoopy cuddles"],["Sprout","sprout cuddle"],
["Sugar","sugar sweet"],["Tiny","tiny cuddle"],["Winnie","winnie cuddles"],["Yogi","yogi cuddles"],["Babe","babe cuddles"],
["Cuddle","cuddle bug"],["Dimple","dimple cuddle"],["Butterscotch","butterscotch sweet"],["Caramel","caramel cuddle"],["Toffee","toffee sweet"],
["Snuggles","snuggles boy"],["Honeybear","honey bear cuddle"]
],
      "adventurous": [
["Atlas","world explorer"],["Hunter","hunter of adventure"],["Legend","legendary explorer"],["Scout","scout explorer"],["Rover","roving adventurer"],
["Orion","star explorer"],["Pioneer","pioneer explorer"],["Seeker","seeker of fun"],["Travis","trekking traveler"],["Voyage","voyage traveler"],
["Walker","walking adventurer"],["Wilder","wild explorer"],["Wyatt","wyatt wanderer"],["Axel","ax-wielding explorer"],["Baron","baron explorer"],
["Explorer","explorer name"],["Nomad","nomadic wanderer"],["Ranger","ranger explorer"],["Trekker","trekking explorer"],["Advent","advent adventurer"],
["Argus","argus explorer"],["Boone","boone explorer"],["Captain","captain explorer"],["Cobalt","cobalt explorer"],["Convoy","convoy explorer"],
["Cross","cross explorer"],["Drake","drake explorer"],["Everest","everest explorer"],["Frontier","frontier explorer"],["Galleon","galleon explorer"],
["Hiker","hiker explorer"],["Journey","journey traveler"],["Kepler","kepler explorer"],["Mariner","mariner explorer"],["Navigator","navigator explorer"],
["Outlaw","outlaw explorer"],["Pathfinder","pathfinder explorer"],["Pilot","pilot explorer"],["Quest","quest explorer"],["Rambler","rambling explorer"],
["Sailor","sailor explorer"],["Trapper","trapper explorer"],["Wander","wandering soul"],["Wayfarer","wayfarer explorer"],["West","western explorer"],
["Woodsman","woodsman explorer"],["Yonder","yonder explorer"],["Zephyr","zephyr wind"],["Angus","scottish angus"],["Hamish","highland explorer"]
],
      "shy": [
["Asher","gentle asher"],["Beau","gentle beau"],["Eli","gentle eli"],["Graham","gentle graham"],["Hugo","gentle hugo"],
["Kian","gentle kian"],["Landon","gentle landon"],["Miles","gentle miles"],["Noah","gentle noah"],["Owen","gentle owen"],
["Silas","gentle silas"],["Caspian","gentle caspian"],["Felix","gentle felix"],["Jasper","gentle jasper"],["Aaron","gentle aaron"],
["Amos","gentle amos"],["Arthur","gentle arthur"],["Bram","gentle bram"],["Calvin","gentle calvin"],["Cedric","gentle cedric"],
["Clark","gentle clark"],["Cole","gentle cole"],["Conrad","gentle conrad"],["Cort","gentle cort"],["Dean","gentle dean"],
["Denton","gentle denton"],["Duncan","gentle duncan"],["Edward","gentle edward"],["Ellis","gentle ellis"],["Emerson","gentle emerson"],
["Ervin","gentle ervin"],["Ford","gentle ford"],["Francis","gentle francis"],["Glenn","gentle glenn"],["Grant","gentle grant"],
["Heath","gentle heath"],["Ian","gentle ian"],["Isaac","gentle isaac"],["Joel","gentle joel"],["Jude","gentle jude"],
["Kent","gentle kent"],["Leonard","gentle leonard"],["Lewis","gentle lewis"],["Martin","gentle martin"],["Nathan","gentle nathan"],
["Paul","gentle paul"],["Philip","gentle philip"],["Ralph","gentle ralph"],["Reed","gentle reed"],["Roy","gentle roy"]
],
      "affectionate": [
["Cooper","loving golden"],["Buddy","best friend forever"],["Bear","big loving bear"],["Teddy","loving teddy"],["Charlie","charming love"],
["Bailey","loving bailey"],["Milo","milo the loving"],["Oliver","loving oliver"],["Riley","loving riley"],["Tucker","loving tucker"],
["Max","loving max"],["Sam","loving sam"],["Louie","loving louie"],["Henry","loving henry"],["Jackson","loving jackson"],
["Leo","loving lion"],["Milo","sweet milo"],["Ollie","loving ollie"],["Bentley","loving bentley"],["Finn","loving finn"],
["Archie","loving archie"],["Gus","loving gus"],["Hank","loving hank"],["Jasper","loving jasper"],["Loki","loving loki"],
["Dexter","loving dexter"],["Murphy","loving murphy"],["Winston","loving winston"],["Cody","loving cody"],["Dakota","loving dakota"],
["Oakley","loving oakley"],["Ranger","loving ranger"],["Scout","loving scout"],["Theo","loving theo"],["Toby","loving toby"],
["Wally","loving wally"],["Ziggy","loving ziggy"],["Augie","loving augie"],["Benny","loving benny"],["Clyde","loving clyde"],
["Dune","loving dune"],["Harley","loving harley"],["Marley","loving marley"],["Ranger","loving ranger"],["Skipper","loving skipper"],
["Biscuit","loving biscuit"],["Honey","loving honey"],["Butters","loving butters"],["Sunny","loving sunny"],["Angus","loving angus"]
]
    },
    "labrador": {
      "playful": [
["Biscuit","golden playful pup"],["Sunny","sunshine golden boy"],["Marley","bob marley vibes"],["Cooper","friendly cooper"],["Tucker","tuckered from play"],
["Charlie","charming charlie"],["Milo","milo the playful"],["Otis","playful otis"],["Teddy","teddy the playful"],["Bailey","bailey the playful"],
["Riley","riley the playful"],["Henry","henry the playful"],["Oliver","oliver the playful"],["Archie","archie the playful"],["Dexter","dex the playful"],
["Finn","finn the playful"],["Louie","louie the playful"],["Gus","gus the playful"],["Ziggy","ziggy the playful"],["Cody","cody the playful"],
["Toby","toby the playful"],["Rex","rex the playful"],["Benny","benny the playful"],["Jasper","jasper the playful"],["Loki","loki the playful"],
["Bentley","bentley the playful"],["Leo","leo the playful"],["Hank","hank the playful"],["Caramel","caramel-coated pup"],["Tanner","golden tanner"],
["Sandy","sandy the playful"],["Butters","butterscotch boy"],["Amber","amber the playful"],["Honey","honey the playful"],["Blaze","golden blaze"],
["Skipper","skipping pup"],["Augie","august golden"],["Juno","juno the playful"],["Brooks","brookside pup"],["Clyde","clyde the playful"],
["Angus","scottish angus"],["Brio","brio the playful"],["Bounce","bouncy golden"],["Flicker","flickering playful"],["Rolly","rolly polly pup"],
["Dune","dune the playful"],["Wally","wally the playful"],["Tater","tater the playful"],["Nugget","golden nugget"],["Bingo","bingo the playful"]
],
      "energetic": [
["Blaze","fiery golden"],["Dakota","dakota the runner"],["Ranger","ranger energy"],["Trek","trekking golden"],["Chase","chase the retriever"],
["Dash","dash the retriever"],["Canyon","canyon the runner"],["Rio","rio energy"],["Sprint","sprinting retriever"],["Maverick","maverick energy"],
["Bolt","bolt speed"],["Flash","flash the retriever"],["Storm","stormy retriever"],["Comet","comet the runner"],["Rocket","rocket energy"],
["Arrow","arrow the retriever"],["Hawk","hawk-eyed hunter"],["Strider","long strider"],["Gallop","galloping golden"],["River","river runner"],
["Rush","rushing energy"],["Titan","titanic golden"],["Trekker","trekking retriever"],["Phoenix","phoenix rising"],["Rebel","rebel runner"],
["Jet","jet speed"],["Thor","thunder energy"],["Brisk","brisk pace"],["Dune","dune runner"],["Clyde","clyde energy"],
["Boomer","boomer energy"],["Bandit","bandit runner"],["Vortex","vortex energy"],["Cyclone","cyclone energy"],["Dynamo","dynamo power"],
["Spark","spark energy"],["Surge","surge energy"],["Fury","fury energy"],["Flash","flash speed"],["Stride","strider energy"],
["Charger","charger energy"],["Wild","wild energy"],["Zest","zesty runner"],["Comet","comet speed"],["Maverick","maverick speed"],
["Marathon","marathon runner"],["Cascade","cascade energy"],["Glen","glen runner"],["Boulder","boulder strength"],["Summit","summit reacher"],
["Pioneer","pioneer runner"],["Viking","viking runner"],["Mariner","mariner explorer"],["Skipper","skipper retriever"]
],
      "cuddly": [
["Bear","big cuddly bear"],["Teddy","teddy bear cuddle"],["Milo","sweet cuddle bug"],["Ollie","cuddly ollie"],["Charlie","charming cuddle"],
["Sammy","sweet cuddles"],["Benny","benny cuddles"],["Cubby","cubby cuddle"],["Muffin","sweet muffin"],["Pebble","pebble cuddle"],
["Sunny","sunny cuddles"],["Lucky","lucky cuddle"],["Leo","lion cuddle"],["Coby","coby cuddles"],["Archie","archie cuddle"],
["Cooper","cooper cuddles"],["Gus","gus cuddles"],["Louie","louie cuddles"],["Theo","theo cuddles"],["Woody","woody cuddles"],
["Bean","bean cuddle"],["Biscuit","biscuit cuddle"],["Bonbon","sweet bonbon"],["Bubba","bubba cuddles"],["Clover","clover cuddle"],
["Dino","dino cuddles"],["Dotty","dotty cuddles"],["Fluff","fluffy cuddle"],["Fudge","fudge sweet"],["Honey","honey sweet"],
["Jaxie","jaxie cuddles"],["Juno","juno cuddles"],["Mochi","sweet mochi"],["Nibs","nibs sweet"],["Nutty","nutty sweet"],
["Peanut","peanut sweet"],["Puff","puffy cuddle"],["Roo","roo cuddle"],["Snoopy","snoopy cuddles"],["Sprout","sprout cuddle"],
["Sugar","sugar sweet"],["Tiny","tiny cuddle"],["Winnie","winnie cuddles"],["Yogi","yogi cuddles"],["Babe","babe cuddles"],
["Cuddle","cuddle bug"],["Dimple","dimple cuddle"],["Butterscotch","butterscotch sweet"],["Caramel","caramel cuddle"],["Toffee","toffee sweet"],
["Snuggles","snuggles boy"],["Honeybear","honey bear cuddle"]
],
      "adventurous": [
["Atlas","world explorer"],["Hunter","hunter of adventure"],["Legend","legendary explorer"],["Scout","scout explorer"],["Rover","roving adventurer"],
["Orion","star explorer"],["Pioneer","pioneer explorer"],["Seeker","seeker of fun"],["Travis","trekking traveler"],["Voyage","voyage traveler"],
["Walker","walking adventurer"],["Wilder","wild explorer"],["Wyatt","wyatt wanderer"],["Axel","ax-wielding explorer"],["Baron","baron explorer"],
["Explorer","explorer name"],["Nomad","nomadic wanderer"],["Ranger","ranger explorer"],["Trekker","trekking explorer"],["Advent","advent adventurer"],
["Argus","argus explorer"],["Boone","boone explorer"],["Captain","captain explorer"],["Cobalt","cobalt explorer"],["Convoy","convoy explorer"],
["Cross","cross explorer"],["Drake","drake explorer"],["Everest","everest explorer"],["Frontier","frontier explorer"],["Galleon","galleon explorer"],
["Hiker","hiker explorer"],["Journey","journey traveler"],["Kepler","kepler explorer"],["Mariner","mariner explorer"],["Navigator","navigator explorer"],
["Outlaw","outlaw explorer"],["Pathfinder","pathfinder explorer"],["Pilot","pilot explorer"],["Quest","quest explorer"],["Rambler","rambling explorer"],
["Sailor","sailor explorer"],["Trapper","trapper explorer"],["Wander","wandering soul"],["Wayfarer","wayfarer explorer"],["West","western explorer"],
["Woodsman","woodsman explorer"],["Yonder","yonder explorer"],["Zephyr","zephyr wind"],["Angus","scottish angus"],["Hamish","highland explorer"]
],
      "shy": [
["Asher","gentle asher"],["Beau","gentle beau"],["Eli","gentle eli"],["Graham","gentle graham"],["Hugo","gentle hugo"],
["Kian","gentle kian"],["Landon","gentle landon"],["Miles","gentle miles"],["Noah","gentle noah"],["Owen","gentle owen"],
["Silas","gentle silas"],["Caspian","gentle caspian"],["Felix","gentle felix"],["Jasper","gentle jasper"],["Aaron","gentle aaron"],
["Amos","gentle amos"],["Arthur","gentle arthur"],["Bram","gentle bram"],["Calvin","gentle calvin"],["Cedric","gentle cedric"],
["Clark","gentle clark"],["Cole","gentle cole"],["Conrad","gentle conrad"],["Cort","gentle cort"],["Dean","gentle dean"],
["Denton","gentle denton"],["Duncan","gentle duncan"],["Edward","gentle edward"],["Ellis","gentle ellis"],["Emerson","gentle emerson"],
["Ervin","gentle ervin"],["Ford","gentle ford"],["Francis","gentle francis"],["Glenn","gentle glenn"],["Grant","gentle grant"],
["Heath","gentle heath"],["Ian","gentle ian"],["Isaac","gentle isaac"],["Joel","gentle joel"],["Jude","gentle jude"],
["Kent","gentle kent"],["Leonard","gentle leonard"],["Lewis","gentle lewis"],["Martin","gentle martin"],["Nathan","gentle nathan"],
["Paul","gentle paul"],["Philip","gentle philip"],["Ralph","gentle ralph"],["Reed","gentle reed"],["Roy","gentle roy"]
],
      "affectionate": [
["Cooper","loving golden"],["Buddy","best friend forever"],["Bear","big loving bear"],["Teddy","loving teddy"],["Charlie","charming love"],
["Bailey","loving bailey"],["Milo","milo the loving"],["Oliver","loving oliver"],["Riley","loving riley"],["Tucker","loving tucker"],
["Max","loving max"],["Sam","loving sam"],["Louie","loving louie"],["Henry","loving henry"],["Jackson","loving jackson"],
["Leo","loving lion"],["Milo","sweet milo"],["Ollie","loving ollie"],["Bentley","loving bentley"],["Finn","loving finn"],
["Archie","loving archie"],["Gus","loving gus"],["Hank","loving hank"],["Jasper","loving jasper"],["Loki","loving loki"],
["Dexter","loving dexter"],["Murphy","loving murphy"],["Winston","loving winston"],["Cody","loving cody"],["Dakota","loving dakota"],
["Oakley","loving oakley"],["Ranger","loving ranger"],["Scout","loving scout"],["Theo","loving theo"],["Toby","loving toby"],
["Wally","loving wally"],["Ziggy","loving ziggy"],["Augie","loving augie"],["Benny","loving benny"],["Clyde","loving clyde"],
["Dune","loving dune"],["Harley","loving harley"],["Marley","loving marley"],["Ranger","loving ranger"],["Skipper","loving skipper"],
["Biscuit","loving biscuit"],["Honey","loving honey"],["Butters","loving butters"],["Sunny","loving sunny"],["Angus","loving angus"]
]
    },
    "french_bulldog": {
      "playful": [
["Biscuit","golden playful pup"],["Sunny","sunshine golden boy"],["Marley","bob marley vibes"],["Cooper","friendly cooper"],["Tucker","tuckered from play"],
["Charlie","charming charlie"],["Milo","milo the playful"],["Otis","playful otis"],["Teddy","teddy the playful"],["Bailey","bailey the playful"],
["Riley","riley the playful"],["Henry","henry the playful"],["Oliver","oliver the playful"],["Archie","archie the playful"],["Dexter","dex the playful"],
["Finn","finn the playful"],["Louie","louie the playful"],["Gus","gus the playful"],["Ziggy","ziggy the playful"],["Cody","cody the playful"],
["Toby","toby the playful"],["Rex","rex the playful"],["Benny","benny the playful"],["Jasper","jasper the playful"],["Loki","loki the playful"],
["Bentley","bentley the playful"],["Leo","leo the playful"],["Hank","hank the playful"],["Caramel","caramel-coated pup"],["Tanner","golden tanner"],
["Sandy","sandy the playful"],["Butters","butterscotch boy"],["Amber","amber the playful"],["Honey","honey the playful"],["Blaze","golden blaze"],
["Skipper","skipping pup"],["Augie","august golden"],["Juno","juno the playful"],["Brooks","brookside pup"],["Clyde","clyde the playful"],
["Angus","scottish angus"],["Brio","brio the playful"],["Bounce","bouncy golden"],["Flicker","flickering playful"],["Rolly","rolly polly pup"],
["Dune","dune the playful"],["Wally","wally the playful"],["Tater","tater the playful"],["Nugget","golden nugget"],["Bingo","bingo the playful"]
],
      "energetic": [
["Blaze","fiery golden"],["Dakota","dakota the runner"],["Ranger","ranger energy"],["Trek","trekking golden"],["Chase","chase the retriever"],
["Dash","dash the retriever"],["Canyon","canyon the runner"],["Rio","rio energy"],["Sprint","sprinting retriever"],["Maverick","maverick energy"],
["Bolt","bolt speed"],["Flash","flash the retriever"],["Storm","stormy retriever"],["Comet","comet the runner"],["Rocket","rocket energy"],
["Arrow","arrow the retriever"],["Hawk","hawk-eyed hunter"],["Strider","long strider"],["Gallop","galloping golden"],["River","river runner"],
["Rush","rushing energy"],["Titan","titanic golden"],["Trekker","trekking retriever"],["Phoenix","phoenix rising"],["Rebel","rebel runner"],
["Jet","jet speed"],["Thor","thunder energy"],["Brisk","brisk pace"],["Dune","dune runner"],["Clyde","clyde energy"],
["Boomer","boomer energy"],["Bandit","bandit runner"],["Vortex","vortex energy"],["Cyclone","cyclone energy"],["Dynamo","dynamo power"],
["Spark","spark energy"],["Surge","surge energy"],["Fury","fury energy"],["Flash","flash speed"],["Stride","strider energy"],
["Charger","charger energy"],["Wild","wild energy"],["Zest","zesty runner"],["Comet","comet speed"],["Maverick","maverick speed"],
["Marathon","marathon runner"],["Cascade","cascade energy"],["Glen","glen runner"],["Boulder","boulder strength"],["Summit","summit reacher"],
["Pioneer","pioneer runner"],["Viking","viking runner"],["Mariner","mariner explorer"],["Skipper","skipper retriever"]
],
      "cuddly": [
["Bear","big cuddly bear"],["Teddy","teddy bear cuddle"],["Milo","sweet cuddle bug"],["Ollie","cuddly ollie"],["Charlie","charming cuddle"],
["Sammy","sweet cuddles"],["Benny","benny cuddles"],["Cubby","cubby cuddle"],["Muffin","sweet muffin"],["Pebble","pebble cuddle"],
["Sunny","sunny cuddles"],["Lucky","lucky cuddle"],["Leo","lion cuddle"],["Coby","coby cuddles"],["Archie","archie cuddle"],
["Cooper","cooper cuddles"],["Gus","gus cuddles"],["Louie","louie cuddles"],["Theo","theo cuddles"],["Woody","woody cuddles"],
["Bean","bean cuddle"],["Biscuit","biscuit cuddle"],["Bonbon","sweet bonbon"],["Bubba","bubba cuddles"],["Clover","clover cuddle"],
["Dino","dino cuddles"],["Dotty","dotty cuddles"],["Fluff","fluffy cuddle"],["Fudge","fudge sweet"],["Honey","honey sweet"],
["Jaxie","jaxie cuddles"],["Juno","juno cuddles"],["Mochi","sweet mochi"],["Nibs","nibs sweet"],["Nutty","nutty sweet"],
["Peanut","peanut sweet"],["Puff","puffy cuddle"],["Roo","roo cuddle"],["Snoopy","snoopy cuddles"],["Sprout","sprout cuddle"],
["Sugar","sugar sweet"],["Tiny","tiny cuddle"],["Winnie","winnie cuddles"],["Yogi","yogi cuddles"],["Babe","babe cuddles"],
["Cuddle","cuddle bug"],["Dimple","dimple cuddle"],["Butterscotch","butterscotch sweet"],["Caramel","caramel cuddle"],["Toffee","toffee sweet"],
["Snuggles","snuggles boy"],["Honeybear","honey bear cuddle"]
],
      "adventurous": [
["Atlas","world explorer"],["Hunter","hunter of adventure"],["Legend","legendary explorer"],["Scout","scout explorer"],["Rover","roving adventurer"],
["Orion","star explorer"],["Pioneer","pioneer explorer"],["Seeker","seeker of fun"],["Travis","trekking traveler"],["Voyage","voyage traveler"],
["Walker","walking adventurer"],["Wilder","wild explorer"],["Wyatt","wyatt wanderer"],["Axel","ax-wielding explorer"],["Baron","baron explorer"],
["Explorer","explorer name"],["Nomad","nomadic wanderer"],["Ranger","ranger explorer"],["Trekker","trekking explorer"],["Advent","advent adventurer"],
["Argus","argus explorer"],["Boone","boone explorer"],["Captain","captain explorer"],["Cobalt","cobalt explorer"],["Convoy","convoy explorer"],
["Cross","cross explorer"],["Drake","drake explorer"],["Everest","everest explorer"],["Frontier","frontier explorer"],["Galleon","galleon explorer"],
["Hiker","hiker explorer"],["Journey","journey traveler"],["Kepler","kepler explorer"],["Mariner","mariner explorer"],["Navigator","navigator explorer"],
["Outlaw","outlaw explorer"],["Pathfinder","pathfinder explorer"],["Pilot","pilot explorer"],["Quest","quest explorer"],["Rambler","rambling explorer"],
["Sailor","sailor explorer"],["Trapper","trapper explorer"],["Wander","wandering soul"],["Wayfarer","wayfarer explorer"],["West","western explorer"],
["Woodsman","woodsman explorer"],["Yonder","yonder explorer"],["Zephyr","zephyr wind"],["Angus","scottish angus"],["Hamish","highland explorer"]
],
      "shy": [
["Asher","gentle asher"],["Beau","gentle beau"],["Eli","gentle eli"],["Graham","gentle graham"],["Hugo","gentle hugo"],
["Kian","gentle kian"],["Landon","gentle landon"],["Miles","gentle miles"],["Noah","gentle noah"],["Owen","gentle owen"],
["Silas","gentle silas"],["Caspian","gentle caspian"],["Felix","gentle felix"],["Jasper","gentle jasper"],["Aaron","gentle aaron"],
["Amos","gentle amos"],["Arthur","gentle arthur"],["Bram","gentle bram"],["Calvin","gentle calvin"],["Cedric","gentle cedric"],
["Clark","gentle clark"],["Cole","gentle cole"],["Conrad","gentle conrad"],["Cort","gentle cort"],["Dean","gentle dean"],
["Denton","gentle denton"],["Duncan","gentle duncan"],["Edward","gentle edward"],["Ellis","gentle ellis"],["Emerson","gentle emerson"],
["Ervin","gentle ervin"],["Ford","gentle ford"],["Francis","gentle francis"],["Glenn","gentle glenn"],["Grant","gentle grant"],
["Heath","gentle heath"],["Ian","gentle ian"],["Isaac","gentle isaac"],["Joel","gentle joel"],["Jude","gentle jude"],
["Kent","gentle kent"],["Leonard","gentle leonard"],["Lewis","gentle lewis"],["Martin","gentle martin"],["Nathan","gentle nathan"],
["Paul","gentle paul"],["Philip","gentle philip"],["Ralph","gentle ralph"],["Reed","gentle reed"],["Roy","gentle roy"]
],
      "affectionate": [
["Cooper","loving golden"],["Buddy","best friend forever"],["Bear","big loving bear"],["Teddy","loving teddy"],["Charlie","charming love"],
["Bailey","loving bailey"],["Milo","milo the loving"],["Oliver","loving oliver"],["Riley","loving riley"],["Tucker","loving tucker"],
["Max","loving max"],["Sam","loving sam"],["Louie","loving louie"],["Henry","loving henry"],["Jackson","loving jackson"],
["Leo","loving lion"],["Milo","sweet milo"],["Ollie","loving ollie"],["Bentley","loving bentley"],["Finn","loving finn"],
["Archie","loving archie"],["Gus","loving gus"],["Hank","loving hank"],["Jasper","loving jasper"],["Loki","loving loki"],
["Dexter","loving dexter"],["Murphy","loving murphy"],["Winston","loving winston"],["Cody","loving cody"],["Dakota","loving dakota"],
["Oakley","loving oakley"],["Ranger","loving ranger"],["Scout","loving scout"],["Theo","loving theo"],["Toby","loving toby"],
["Wally","loving wally"],["Ziggy","loving ziggy"],["Augie","loving augie"],["Benny","loving benny"],["Clyde","loving clyde"],
["Dune","loving dune"],["Harley","loving harley"],["Marley","loving marley"],["Ranger","loving ranger"],["Skipper","loving skipper"],
["Biscuit","loving biscuit"],["Honey","loving honey"],["Butters","loving butters"],["Sunny","loving sunny"],["Angus","loving angus"]
]
    },
    "chihuahua": {
      "playful": [
["Biscuit","golden playful pup"],["Sunny","sunshine golden boy"],["Marley","bob marley vibes"],["Cooper","friendly cooper"],["Tucker","tuckered from play"],
["Charlie","charming charlie"],["Milo","milo the playful"],["Otis","playful otis"],["Teddy","teddy the playful"],["Bailey","bailey the playful"],
["Riley","riley the playful"],["Henry","henry the playful"],["Oliver","oliver the playful"],["Archie","archie the playful"],["Dexter","dex the playful"],
["Finn","finn the playful"],["Louie","louie the playful"],["Gus","gus the playful"],["Ziggy","ziggy the playful"],["Cody","cody the playful"],
["Toby","toby the playful"],["Rex","rex the playful"],["Benny","benny the playful"],["Jasper","jasper the playful"],["Loki","loki the playful"],
["Bentley","bentley the playful"],["Leo","leo the playful"],["Hank","hank the playful"],["Caramel","caramel-coated pup"],["Tanner","golden tanner"],
["Sandy","sandy the playful"],["Butters","butterscotch boy"],["Amber","amber the playful"],["Honey","honey the playful"],["Blaze","golden blaze"],
["Skipper","skipping pup"],["Augie","august golden"],["Juno","juno the playful"],["Brooks","brookside pup"],["Clyde","clyde the playful"],
["Angus","scottish angus"],["Brio","brio the playful"],["Bounce","bouncy golden"],["Flicker","flickering playful"],["Rolly","rolly polly pup"],
["Dune","dune the playful"],["Wally","wally the playful"],["Tater","tater the playful"],["Nugget","golden nugget"],["Bingo","bingo the playful"]
],
      "energetic": [
["Blaze","fiery golden"],["Dakota","dakota the runner"],["Ranger","ranger energy"],["Trek","trekking golden"],["Chase","chase the retriever"],
["Dash","dash the retriever"],["Canyon","canyon the runner"],["Rio","rio energy"],["Sprint","sprinting retriever"],["Maverick","maverick energy"],
["Bolt","bolt speed"],["Flash","flash the retriever"],["Storm","stormy retriever"],["Comet","comet the runner"],["Rocket","rocket energy"],
["Arrow","arrow the retriever"],["Hawk","hawk-eyed hunter"],["Strider","long strider"],["Gallop","galloping golden"],["River","river runner"],
["Rush","rushing energy"],["Titan","titanic golden"],["Trekker","trekking retriever"],["Phoenix","phoenix rising"],["Rebel","rebel runner"],
["Jet","jet speed"],["Thor","thunder energy"],["Brisk","brisk pace"],["Dune","dune runner"],["Clyde","clyde energy"],
["Boomer","boomer energy"],["Bandit","bandit runner"],["Vortex","vortex energy"],["Cyclone","cyclone energy"],["Dynamo","dynamo power"],
["Spark","spark energy"],["Surge","surge energy"],["Fury","fury energy"],["Flash","flash speed"],["Stride","strider energy"],
["Charger","charger energy"],["Wild","wild energy"],["Zest","zesty runner"],["Comet","comet speed"],["Maverick","maverick speed"],
["Marathon","marathon runner"],["Cascade","cascade energy"],["Glen","glen runner"],["Boulder","boulder strength"],["Summit","summit reacher"],
["Pioneer","pioneer runner"],["Viking","viking runner"],["Mariner","mariner explorer"],["Skipper","skipper retriever"]
],
      "cuddly": [
["Bear","big cuddly bear"],["Teddy","teddy bear cuddle"],["Milo","sweet cuddle bug"],["Ollie","cuddly ollie"],["Charlie","charming cuddle"],
["Sammy","sweet cuddles"],["Benny","benny cuddles"],["Cubby","cubby cuddle"],["Muffin","sweet muffin"],["Pebble","pebble cuddle"],
["Sunny","sunny cuddles"],["Lucky","lucky cuddle"],["Leo","lion cuddle"],["Coby","coby cuddles"],["Archie","archie cuddle"],
["Cooper","cooper cuddles"],["Gus","gus cuddles"],["Louie","louie cuddles"],["Theo","theo cuddles"],["Woody","woody cuddles"],
["Bean","bean cuddle"],["Biscuit","biscuit cuddle"],["Bonbon","sweet bonbon"],["Bubba","bubba cuddles"],["Clover","clover cuddle"],
["Dino","dino cuddles"],["Dotty","dotty cuddles"],["Fluff","fluffy cuddle"],["Fudge","fudge sweet"],["Honey","honey sweet"],
["Jaxie","jaxie cuddles"],["Juno","juno cuddles"],["Mochi","sweet mochi"],["Nibs","nibs sweet"],["Nutty","nutty sweet"],
["Peanut","peanut sweet"],["Puff","puffy cuddle"],["Roo","roo cuddle"],["Snoopy","snoopy cuddles"],["Sprout","sprout cuddle"],
["Sugar","sugar sweet"],["Tiny","tiny cuddle"],["Winnie","winnie cuddles"],["Yogi","yogi cuddles"],["Babe","babe cuddles"],
["Cuddle","cuddle bug"],["Dimple","dimple cuddle"],["Butterscotch","butterscotch sweet"],["Caramel","caramel cuddle"],["Toffee","toffee sweet"],
["Snuggles","snuggles boy"],["Honeybear","honey bear cuddle"]
],
      "adventurous": [
["Atlas","world explorer"],["Hunter","hunter of adventure"],["Legend","legendary explorer"],["Scout","scout explorer"],["Rover","roving adventurer"],
["Orion","star explorer"],["Pioneer","pioneer explorer"],["Seeker","seeker of fun"],["Travis","trekking traveler"],["Voyage","voyage traveler"],
["Walker","walking adventurer"],["Wilder","wild explorer"],["Wyatt","wyatt wanderer"],["Axel","ax-wielding explorer"],["Baron","baron explorer"],
["Explorer","explorer name"],["Nomad","nomadic wanderer"],["Ranger","ranger explorer"],["Trekker","trekking explorer"],["Advent","advent adventurer"],
["Argus","argus explorer"],["Boone","boone explorer"],["Captain","captain explorer"],["Cobalt","cobalt explorer"],["Convoy","convoy explorer"],
["Cross","cross explorer"],["Drake","drake explorer"],["Everest","everest explorer"],["Frontier","frontier explorer"],["Galleon","galleon explorer"],
["Hiker","hiker explorer"],["Journey","journey traveler"],["Kepler","kepler explorer"],["Mariner","mariner explorer"],["Navigator","navigator explorer"],
["Outlaw","outlaw explorer"],["Pathfinder","pathfinder explorer"],["Pilot","pilot explorer"],["Quest","quest explorer"],["Rambler","rambling explorer"],
["Sailor","sailor explorer"],["Trapper","trapper explorer"],["Wander","wandering soul"],["Wayfarer","wayfarer explorer"],["West","western explorer"],
["Woodsman","woodsman explorer"],["Yonder","yonder explorer"],["Zephyr","zephyr wind"],["Angus","scottish angus"],["Hamish","highland explorer"]
],
      "shy": [
["Asher","gentle asher"],["Beau","gentle beau"],["Eli","gentle eli"],["Graham","gentle graham"],["Hugo","gentle hugo"],
["Kian","gentle kian"],["Landon","gentle landon"],["Miles","gentle miles"],["Noah","gentle noah"],["Owen","gentle owen"],
["Silas","gentle silas"],["Caspian","gentle caspian"],["Felix","gentle felix"],["Jasper","gentle jasper"],["Aaron","gentle aaron"],
["Amos","gentle amos"],["Arthur","gentle arthur"],["Bram","gentle bram"],["Calvin","gentle calvin"],["Cedric","gentle cedric"],
["Clark","gentle clark"],["Cole","gentle cole"],["Conrad","gentle conrad"],["Cort","gentle cort"],["Dean","gentle dean"],
["Denton","gentle denton"],["Duncan","gentle duncan"],["Edward","gentle edward"],["Ellis","gentle ellis"],["Emerson","gentle emerson"],
["Ervin","gentle ervin"],["Ford","gentle ford"],["Francis","gentle francis"],["Glenn","gentle glenn"],["Grant","gentle grant"],
["Heath","gentle heath"],["Ian","gentle ian"],["Isaac","gentle isaac"],["Joel","gentle joel"],["Jude","gentle jude"],
["Kent","gentle kent"],["Leonard","gentle leonard"],["Lewis","gentle lewis"],["Martin","gentle martin"],["Nathan","gentle nathan"],
["Paul","gentle paul"],["Philip","gentle philip"],["Ralph","gentle ralph"],["Reed","gentle reed"],["Roy","gentle roy"]
],
      "affectionate": [
["Cooper","loving golden"],["Buddy","best friend forever"],["Bear","big loving bear"],["Teddy","loving teddy"],["Charlie","charming love"],
["Bailey","loving bailey"],["Milo","milo the loving"],["Oliver","loving oliver"],["Riley","loving riley"],["Tucker","loving tucker"],
["Max","loving max"],["Sam","loving sam"],["Louie","loving louie"],["Henry","loving henry"],["Jackson","loving jackson"],
["Leo","loving lion"],["Milo","sweet milo"],["Ollie","loving ollie"],["Bentley","loving bentley"],["Finn","loving finn"],
["Archie","loving archie"],["Gus","loving gus"],["Hank","loving hank"],["Jasper","loving jasper"],["Loki","loving loki"],
["Dexter","loving dexter"],["Murphy","loving murphy"],["Winston","loving winston"],["Cody","loving cody"],["Dakota","loving dakota"],
["Oakley","loving oakley"],["Ranger","loving ranger"],["Scout","loving scout"],["Theo","loving theo"],["Toby","loving toby"],
["Wally","loving wally"],["Ziggy","loving ziggy"],["Augie","loving augie"],["Benny","loving benny"],["Clyde","loving clyde"],
["Dune","loving dune"],["Harley","loving harley"],["Marley","loving marley"],["Ranger","loving ranger"],["Skipper","loving skipper"],
["Biscuit","loving biscuit"],["Honey","loving honey"],["Butters","loving butters"],["Sunny","loving sunny"],["Angus","loving angus"]
]
    },
    "german_shepherd": {
      "playful": [
["Biscuit","golden playful pup"],["Sunny","sunshine golden boy"],["Marley","bob marley vibes"],["Cooper","friendly cooper"],["Tucker","tuckered from play"],
["Charlie","charming charlie"],["Milo","milo the playful"],["Otis","playful otis"],["Teddy","teddy the playful"],["Bailey","bailey the playful"],
["Riley","riley the playful"],["Henry","henry the playful"],["Oliver","oliver the playful"],["Archie","archie the playful"],["Dexter","dex the playful"],
["Finn","finn the playful"],["Louie","louie the playful"],["Gus","gus the playful"],["Ziggy","ziggy the playful"],["Cody","cody the playful"],
["Toby","toby the playful"],["Rex","rex the playful"],["Benny","benny the playful"],["Jasper","jasper the playful"],["Loki","loki the playful"],
["Bentley","bentley the playful"],["Leo","leo the playful"],["Hank","hank the playful"],["Caramel","caramel-coated pup"],["Tanner","golden tanner"],
["Sandy","sandy the playful"],["Butters","butterscotch boy"],["Amber","amber the playful"],["Honey","honey the playful"],["Blaze","golden blaze"],
["Skipper","skipping pup"],["Augie","august golden"],["Juno","juno the playful"],["Brooks","brookside pup"],["Clyde","clyde the playful"],
["Angus","scottish angus"],["Brio","brio the playful"],["Bounce","bouncy golden"],["Flicker","flickering playful"],["Rolly","rolly polly pup"],
["Dune","dune the playful"],["Wally","wally the playful"],["Tater","tater the playful"],["Nugget","golden nugget"],["Bingo","bingo the playful"]
],
      "energetic": [
["Blaze","fiery golden"],["Dakota","dakota the runner"],["Ranger","ranger energy"],["Trek","trekking golden"],["Chase","chase the retriever"],
["Dash","dash the retriever"],["Canyon","canyon the runner"],["Rio","rio energy"],["Sprint","sprinting retriever"],["Maverick","maverick energy"],
["Bolt","bolt speed"],["Flash","flash the retriever"],["Storm","stormy retriever"],["Comet","comet the runner"],["Rocket","rocket energy"],
["Arrow","arrow the retriever"],["Hawk","hawk-eyed hunter"],["Strider","long strider"],["Gallop","galloping golden"],["River","river runner"],
["Rush","rushing energy"],["Titan","titanic golden"],["Trekker","trekking retriever"],["Phoenix","phoenix rising"],["Rebel","rebel runner"],
["Jet","jet speed"],["Thor","thunder energy"],["Brisk","brisk pace"],["Dune","dune runner"],["Clyde","clyde energy"],
["Boomer","boomer energy"],["Bandit","bandit runner"],["Vortex","vortex energy"],["Cyclone","cyclone energy"],["Dynamo","dynamo power"],
["Spark","spark energy"],["Surge","surge energy"],["Fury","fury energy"],["Flash","flash speed"],["Stride","strider energy"],
["Charger","charger energy"],["Wild","wild energy"],["Zest","zesty runner"],["Comet","comet speed"],["Maverick","maverick speed"],
["Marathon","marathon runner"],["Cascade","cascade energy"],["Glen","glen runner"],["Boulder","boulder strength"],["Summit","summit reacher"],
["Pioneer","pioneer runner"],["Viking","viking runner"],["Mariner","mariner explorer"],["Skipper","skipper retriever"]
],
      "cuddly": [
["Bear","big cuddly bear"],["Teddy","teddy bear cuddle"],["Milo","sweet cuddle bug"],["Ollie","cuddly ollie"],["Charlie","charming cuddle"],
["Sammy","sweet cuddles"],["Benny","benny cuddles"],["Cubby","cubby cuddle"],["Muffin","sweet muffin"],["Pebble","pebble cuddle"],
["Sunny","sunny cuddles"],["Lucky","lucky cuddle"],["Leo","lion cuddle"],["Coby","coby cuddles"],["Archie","archie cuddle"],
["Cooper","cooper cuddles"],["Gus","gus cuddles"],["Louie","louie cuddles"],["Theo","theo cuddles"],["Woody","woody cuddles"],
["Bean","bean cuddle"],["Biscuit","biscuit cuddle"],["Bonbon","sweet bonbon"],["Bubba","bubba cuddles"],["Clover","clover cuddle"],
["Dino","dino cuddles"],["Dotty","dotty cuddles"],["Fluff","fluffy cuddle"],["Fudge","fudge sweet"],["Honey","honey sweet"],
["Jaxie","jaxie cuddles"],["Juno","juno cuddles"],["Mochi","sweet mochi"],["Nibs","nibs sweet"],["Nutty","nutty sweet"],
["Peanut","peanut sweet"],["Puff","puffy cuddle"],["Roo","roo cuddle"],["Snoopy","snoopy cuddles"],["Sprout","sprout cuddle"],
["Sugar","sugar sweet"],["Tiny","tiny cuddle"],["Winnie","winnie cuddles"],["Yogi","yogi cuddles"],["Babe","babe cuddles"],
["Cuddle","cuddle bug"],["Dimple","dimple cuddle"],["Butterscotch","butterscotch sweet"],["Caramel","caramel cuddle"],["Toffee","toffee sweet"],
["Snuggles","snuggles boy"],["Honeybear","honey bear cuddle"]
],
      "adventurous": [
["Atlas","world explorer"],["Hunter","hunter of adventure"],["Legend","legendary explorer"],["Scout","scout explorer"],["Rover","roving adventurer"],
["Orion","star explorer"],["Pioneer","pioneer explorer"],["Seeker","seeker of fun"],["Travis","trekking traveler"],["Voyage","voyage traveler"],
["Walker","walking adventurer"],["Wilder","wild explorer"],["Wyatt","wyatt wanderer"],["Axel","ax-wielding explorer"],["Baron","baron explorer"],
["Explorer","explorer name"],["Nomad","nomadic wanderer"],["Ranger","ranger explorer"],["Trekker","trekking explorer"],["Advent","advent adventurer"],
["Argus","argus explorer"],["Boone","boone explorer"],["Captain","captain explorer"],["Cobalt","cobalt explorer"],["Convoy","convoy explorer"],
["Cross","cross explorer"],["Drake","drake explorer"],["Everest","everest explorer"],["Frontier","frontier explorer"],["Galleon","galleon explorer"],
["Hiker","hiker explorer"],["Journey","journey traveler"],["Kepler","kepler explorer"],["Mariner","mariner explorer"],["Navigator","navigator explorer"],
["Outlaw","outlaw explorer"],["Pathfinder","pathfinder explorer"],["Pilot","pilot explorer"],["Quest","quest explorer"],["Rambler","rambling explorer"],
["Sailor","sailor explorer"],["Trapper","trapper explorer"],["Wander","wandering soul"],["Wayfarer","wayfarer explorer"],["West","western explorer"],
["Woodsman","woodsman explorer"],["Yonder","yonder explorer"],["Zephyr","zephyr wind"],["Angus","scottish angus"],["Hamish","highland explorer"]
],
      "shy": [
["Asher","gentle asher"],["Beau","gentle beau"],["Eli","gentle eli"],["Graham","gentle graham"],["Hugo","gentle hugo"],
["Kian","gentle kian"],["Landon","gentle landon"],["Miles","gentle miles"],["Noah","gentle noah"],["Owen","gentle owen"],
["Silas","gentle silas"],["Caspian","gentle caspian"],["Felix","gentle felix"],["Jasper","gentle jasper"],["Aaron","gentle aaron"],
["Amos","gentle amos"],["Arthur","gentle arthur"],["Bram","gentle bram"],["Calvin","gentle calvin"],["Cedric","gentle cedric"],
["Clark","gentle clark"],["Cole","gentle cole"],["Conrad","gentle conrad"],["Cort","gentle cort"],["Dean","gentle dean"],
["Denton","gentle denton"],["Duncan","gentle duncan"],["Edward","gentle edward"],["Ellis","gentle ellis"],["Emerson","gentle emerson"],
["Ervin","gentle ervin"],["Ford","gentle ford"],["Francis","gentle francis"],["Glenn","gentle glenn"],["Grant","gentle grant"],
["Heath","gentle heath"],["Ian","gentle ian"],["Isaac","gentle isaac"],["Joel","gentle joel"],["Jude","gentle jude"],
["Kent","gentle kent"],["Leonard","gentle leonard"],["Lewis","gentle lewis"],["Martin","gentle martin"],["Nathan","gentle nathan"],
["Paul","gentle paul"],["Philip","gentle philip"],["Ralph","gentle ralph"],["Reed","gentle reed"],["Roy","gentle roy"]
],
      "affectionate": [
["Cooper","loving golden"],["Buddy","best friend forever"],["Bear","big loving bear"],["Teddy","loving teddy"],["Charlie","charming love"],
["Bailey","loving bailey"],["Milo","milo the loving"],["Oliver","loving oliver"],["Riley","loving riley"],["Tucker","loving tucker"],
["Max","loving max"],["Sam","loving sam"],["Louie","loving louie"],["Henry","loving henry"],["Jackson","loving jackson"],
["Leo","loving lion"],["Milo","sweet milo"],["Ollie","loving ollie"],["Bentley","loving bentley"],["Finn","loving finn"],
["Archie","loving archie"],["Gus","loving gus"],["Hank","loving hank"],["Jasper","loving jasper"],["Loki","loving loki"],
["Dexter","loving dexter"],["Murphy","loving murphy"],["Winston","loving winston"],["Cody","loving cody"],["Dakota","loving dakota"],
["Oakley","loving oakley"],["Ranger","loving ranger"],["Scout","loving scout"],["Theo","loving theo"],["Toby","loving toby"],
["Wally","loving wally"],["Ziggy","loving ziggy"],["Augie","loving augie"],["Benny","loving benny"],["Clyde","loving clyde"],
["Dune","loving dune"],["Harley","loving harley"],["Marley","loving marley"],["Ranger","loving ranger"],["Skipper","loving skipper"],
["Biscuit","loving biscuit"],["Honey","loving honey"],["Butters","loving butters"],["Sunny","loving sunny"],["Angus","loving angus"]
]
    }
  },
  "female": {
    "golden_retriever": {
      "playful": [
["Biscuit","golden playful pup"],["Sunny","sunshine golden boy"],["Marley","bob marley vibes"],["Cooper","friendly cooper"],["Tucker","tuckered from play"],
["Charlie","charming charlie"],["Milo","milo the playful"],["Otis","playful otis"],["Teddy","teddy the playful"],["Bailey","bailey the playful"],
["Riley","riley the playful"],["Henry","henry the playful"],["Oliver","oliver the playful"],["Archie","archie the playful"],["Dexter","dex the playful"],
["Finn","finn the playful"],["Louie","louie the playful"],["Gus","gus the playful"],["Ziggy","ziggy the playful"],["Cody","cody the playful"],
["Toby","toby the playful"],["Rex","rex the playful"],["Benny","benny the playful"],["Jasper","jasper the playful"],["Loki","loki the playful"],
["Bentley","bentley the playful"],["Leo","leo the playful"],["Hank","hank the playful"],["Caramel","caramel-coated pup"],["Tanner","golden tanner"],
["Sandy","sandy the playful"],["Butters","butterscotch boy"],["Amber","amber the playful"],["Honey","honey the playful"],["Blaze","golden blaze"],
["Skipper","skipping pup"],["Augie","august golden"],["Juno","juno the playful"],["Brooks","brookside pup"],["Clyde","clyde the playful"],
["Angus","scottish angus"],["Brio","brio the playful"],["Bounce","bouncy golden"],["Flicker","flickering playful"],["Rolly","rolly polly pup"],
["Dune","dune the playful"],["Wally","wally the playful"],["Tater","tater the playful"],["Nugget","golden nugget"],["Bingo","bingo the playful"]
],
      "energetic": [
["Blaze","fiery golden"],["Dakota","dakota the runner"],["Ranger","ranger energy"],["Trek","trekking golden"],["Chase","chase the retriever"],
["Dash","dash the retriever"],["Canyon","canyon the runner"],["Rio","rio energy"],["Sprint","sprinting retriever"],["Maverick","maverick energy"],
["Bolt","bolt speed"],["Flash","flash the retriever"],["Storm","stormy retriever"],["Comet","comet the runner"],["Rocket","rocket energy"],
["Arrow","arrow the retriever"],["Hawk","hawk-eyed hunter"],["Strider","long strider"],["Gallop","galloping golden"],["River","river runner"],
["Rush","rushing energy"],["Titan","titanic golden"],["Trekker","trekking retriever"],["Phoenix","phoenix rising"],["Rebel","rebel runner"],
["Jet","jet speed"],["Thor","thunder energy"],["Brisk","brisk pace"],["Dune","dune runner"],["Clyde","clyde energy"],
["Boomer","boomer energy"],["Bandit","bandit runner"],["Vortex","vortex energy"],["Cyclone","cyclone energy"],["Dynamo","dynamo power"],
["Spark","spark energy"],["Surge","surge energy"],["Fury","fury energy"],["Flash","flash speed"],["Stride","strider energy"],
["Charger","charger energy"],["Wild","wild energy"],["Zest","zesty runner"],["Comet","comet speed"],["Maverick","maverick speed"],
["Marathon","marathon runner"],["Cascade","cascade energy"],["Glen","glen runner"],["Boulder","boulder strength"],["Summit","summit reacher"],
["Pioneer","pioneer runner"],["Viking","viking runner"],["Mariner","mariner explorer"],["Skipper","skipper retriever"]
],
      "cuddly": [
["Bear","big cuddly bear"],["Teddy","teddy bear cuddle"],["Milo","sweet cuddle bug"],["Ollie","cuddly ollie"],["Charlie","charming cuddle"],
["Sammy","sweet cuddles"],["Benny","benny cuddles"],["Cubby","cubby cuddle"],["Muffin","sweet muffin"],["Pebble","pebble cuddle"],
["Sunny","sunny cuddles"],["Lucky","lucky cuddle"],["Leo","lion cuddle"],["Coby","coby cuddles"],["Archie","archie cuddle"],
["Cooper","cooper cuddles"],["Gus","gus cuddles"],["Louie","louie cuddles"],["Theo","theo cuddles"],["Woody","woody cuddles"],
["Bean","bean cuddle"],["Biscuit","biscuit cuddle"],["Bonbon","sweet bonbon"],["Bubba","bubba cuddles"],["Clover","clover cuddle"],
["Dino","dino cuddles"],["Dotty","dotty cuddles"],["Fluff","fluffy cuddle"],["Fudge","fudge sweet"],["Honey","honey sweet"],
["Jaxie","jaxie cuddles"],["Juno","juno cuddles"],["Mochi","sweet mochi"],["Nibs","nibs sweet"],["Nutty","nutty sweet"],
["Peanut","peanut sweet"],["Puff","puffy cuddle"],["Roo","roo cuddle"],["Snoopy","snoopy cuddles"],["Sprout","sprout cuddle"],
["Sugar","sugar sweet"],["Tiny","tiny cuddle"],["Winnie","winnie cuddles"],["Yogi","yogi cuddles"],["Babe","babe cuddles"],
["Cuddle","cuddle bug"],["Dimple","dimple cuddle"],["Butterscotch","butterscotch sweet"],["Caramel","caramel cuddle"],["Toffee","toffee sweet"],
["Snuggles","snuggles boy"],["Honeybear","honey bear cuddle"]
],
      "adventurous": [
["Atlas","world explorer"],["Hunter","hunter of adventure"],["Legend","legendary explorer"],["Scout","scout explorer"],["Rover","roving adventurer"],
["Orion","star explorer"],["Pioneer","pioneer explorer"],["Seeker","seeker of fun"],["Travis","trekking traveler"],["Voyage","voyage traveler"],
["Walker","walking adventurer"],["Wilder","wild explorer"],["Wyatt","wyatt wanderer"],["Axel","ax-wielding explorer"],["Baron","baron explorer"],
["Explorer","explorer name"],["Nomad","nomadic wanderer"],["Ranger","ranger explorer"],["Trekker","trekking explorer"],["Advent","advent adventurer"],
["Argus","argus explorer"],["Boone","boone explorer"],["Captain","captain explorer"],["Cobalt","cobalt explorer"],["Convoy","convoy explorer"],
["Cross","cross explorer"],["Drake","drake explorer"],["Everest","everest explorer"],["Frontier","frontier explorer"],["Galleon","galleon explorer"],
["Hiker","hiker explorer"],["Journey","journey traveler"],["Kepler","kepler explorer"],["Mariner","mariner explorer"],["Navigator","navigator explorer"],
["Outlaw","outlaw explorer"],["Pathfinder","pathfinder explorer"],["Pilot","pilot explorer"],["Quest","quest explorer"],["Rambler","rambling explorer"],
["Sailor","sailor explorer"],["Trapper","trapper explorer"],["Wander","wandering soul"],["Wayfarer","wayfarer explorer"],["West","western explorer"],
["Woodsman","woodsman explorer"],["Yonder","yonder explorer"],["Zephyr","zephyr wind"],["Angus","scottish angus"],["Hamish","highland explorer"]
],
      "shy": [
["Asher","gentle asher"],["Beau","gentle beau"],["Eli","gentle eli"],["Graham","gentle graham"],["Hugo","gentle hugo"],
["Kian","gentle kian"],["Landon","gentle landon"],["Miles","gentle miles"],["Noah","gentle noah"],["Owen","gentle owen"],
["Silas","gentle silas"],["Caspian","gentle caspian"],["Felix","gentle felix"],["Jasper","gentle jasper"],["Aaron","gentle aaron"],
["Amos","gentle amos"],["Arthur","gentle arthur"],["Bram","gentle bram"],["Calvin","gentle calvin"],["Cedric","gentle cedric"],
["Clark","gentle clark"],["Cole","gentle cole"],["Conrad","gentle conrad"],["Cort","gentle cort"],["Dean","gentle dean"],
["Denton","gentle denton"],["Duncan","gentle duncan"],["Edward","gentle edward"],["Ellis","gentle ellis"],["Emerson","gentle emerson"],
["Ervin","gentle ervin"],["Ford","gentle ford"],["Francis","gentle francis"],["Glenn","gentle glenn"],["Grant","gentle grant"],
["Heath","gentle heath"],["Ian","gentle ian"],["Isaac","gentle isaac"],["Joel","gentle joel"],["Jude","gentle jude"],
["Kent","gentle kent"],["Leonard","gentle leonard"],["Lewis","gentle lewis"],["Martin","gentle martin"],["Nathan","gentle nathan"],
["Paul","gentle paul"],["Philip","gentle philip"],["Ralph","gentle ralph"],["Reed","gentle reed"],["Roy","gentle roy"]
],
      "affectionate": [
["Cooper","loving golden"],["Buddy","best friend forever"],["Bear","big loving bear"],["Teddy","loving teddy"],["Charlie","charming love"],
["Bailey","loving bailey"],["Milo","milo the loving"],["Oliver","loving oliver"],["Riley","loving riley"],["Tucker","loving tucker"],
["Max","loving max"],["Sam","loving sam"],["Louie","loving louie"],["Henry","loving henry"],["Jackson","loving jackson"],
["Leo","loving lion"],["Milo","sweet milo"],["Ollie","loving ollie"],["Bentley","loving bentley"],["Finn","loving finn"],
["Archie","loving archie"],["Gus","loving gus"],["Hank","loving hank"],["Jasper","loving jasper"],["Loki","loving loki"],
["Dexter","loving dexter"],["Murphy","loving murphy"],["Winston","loving winston"],["Cody","loving cody"],["Dakota","loving dakota"],
["Oakley","loving oakley"],["Ranger","loving ranger"],["Scout","loving scout"],["Theo","loving theo"],["Toby","loving toby"],
["Wally","loving wally"],["Ziggy","loving ziggy"],["Augie","loving augie"],["Benny","loving benny"],["Clyde","loving clyde"],
["Dune","loving dune"],["Harley","loving harley"],["Marley","loving marley"],["Ranger","loving ranger"],["Skipper","loving skipper"],
["Biscuit","loving biscuit"],["Honey","loving honey"],["Butters","loving butters"],["Sunny","loving sunny"],["Angus","loving angus"]
]
    },
    "labrador": {
      "playful": [
["Biscuit","golden playful pup"],["Sunny","sunshine golden boy"],["Marley","bob marley vibes"],["Cooper","friendly cooper"],["Tucker","tuckered from play"],
["Charlie","charming charlie"],["Milo","milo the playful"],["Otis","playful otis"],["Teddy","teddy the playful"],["Bailey","bailey the playful"],
["Riley","riley the playful"],["Henry","henry the playful"],["Oliver","oliver the playful"],["Archie","archie the playful"],["Dexter","dex the playful"],
["Finn","finn the playful"],["Louie","louie the playful"],["Gus","gus the playful"],["Ziggy","ziggy the playful"],["Cody","cody the playful"],
["Toby","toby the playful"],["Rex","rex the playful"],["Benny","benny the playful"],["Jasper","jasper the playful"],["Loki","loki the playful"],
["Bentley","bentley the playful"],["Leo","leo the playful"],["Hank","hank the playful"],["Caramel","caramel-coated pup"],["Tanner","golden tanner"],
["Sandy","sandy the playful"],["Butters","butterscotch boy"],["Amber","amber the playful"],["Honey","honey the playful"],["Blaze","golden blaze"],
["Skipper","skipping pup"],["Augie","august golden"],["Juno","juno the playful"],["Brooks","brookside pup"],["Clyde","clyde the playful"],
["Angus","scottish angus"],["Brio","brio the playful"],["Bounce","bouncy golden"],["Flicker","flickering playful"],["Rolly","rolly polly pup"],
["Dune","dune the playful"],["Wally","wally the playful"],["Tater","tater the playful"],["Nugget","golden nugget"],["Bingo","bingo the playful"]
],
      "energetic": [
["Blaze","fiery golden"],["Dakota","dakota the runner"],["Ranger","ranger energy"],["Trek","trekking golden"],["Chase","chase the retriever"],
["Dash","dash the retriever"],["Canyon","canyon the runner"],["Rio","rio energy"],["Sprint","sprinting retriever"],["Maverick","maverick energy"],
["Bolt","bolt speed"],["Flash","flash the retriever"],["Storm","stormy retriever"],["Comet","comet the runner"],["Rocket","rocket energy"],
["Arrow","arrow the retriever"],["Hawk","hawk-eyed hunter"],["Strider","long strider"],["Gallop","galloping golden"],["River","river runner"],
["Rush","rushing energy"],["Titan","titanic golden"],["Trekker","trekking retriever"],["Phoenix","phoenix rising"],["Rebel","rebel runner"],
["Jet","jet speed"],["Thor","thunder energy"],["Brisk","brisk pace"],["Dune","dune runner"],["Clyde","clyde energy"],
["Boomer","boomer energy"],["Bandit","bandit runner"],["Vortex","vortex energy"],["Cyclone","cyclone energy"],["Dynamo","dynamo power"],
["Spark","spark energy"],["Surge","surge energy"],["Fury","fury energy"],["Flash","flash speed"],["Stride","strider energy"],
["Charger","charger energy"],["Wild","wild energy"],["Zest","zesty runner"],["Comet","comet speed"],["Maverick","maverick speed"],
["Marathon","marathon runner"],["Cascade","cascade energy"],["Glen","glen runner"],["Boulder","boulder strength"],["Summit","summit reacher"],
["Pioneer","pioneer runner"],["Viking","viking runner"],["Mariner","mariner explorer"],["Skipper","skipper retriever"]
],
      "cuddly": [
["Bear","big cuddly bear"],["Teddy","teddy bear cuddle"],["Milo","sweet cuddle bug"],["Ollie","cuddly ollie"],["Charlie","charming cuddle"],
["Sammy","sweet cuddles"],["Benny","benny cuddles"],["Cubby","cubby cuddle"],["Muffin","sweet muffin"],["Pebble","pebble cuddle"],
["Sunny","sunny cuddles"],["Lucky","lucky cuddle"],["Leo","lion cuddle"],["Coby","coby cuddles"],["Archie","archie cuddle"],
["Cooper","cooper cuddles"],["Gus","gus cuddles"],["Louie","louie cuddles"],["Theo","theo cuddles"],["Woody","woody cuddles"],
["Bean","bean cuddle"],["Biscuit","biscuit cuddle"],["Bonbon","sweet bonbon"],["Bubba","bubba cuddles"],["Clover","clover cuddle"],
["Dino","dino cuddles"],["Dotty","dotty cuddles"],["Fluff","fluffy cuddle"],["Fudge","fudge sweet"],["Honey","honey sweet"],
["Jaxie","jaxie cuddles"],["Juno","juno cuddles"],["Mochi","sweet mochi"],["Nibs","nibs sweet"],["Nutty","nutty sweet"],
["Peanut","peanut sweet"],["Puff","puffy cuddle"],["Roo","roo cuddle"],["Snoopy","snoopy cuddles"],["Sprout","sprout cuddle"],
["Sugar","sugar sweet"],["Tiny","tiny cuddle"],["Winnie","winnie cuddles"],["Yogi","yogi cuddles"],["Babe","babe cuddles"],
["Cuddle","cuddle bug"],["Dimple","dimple cuddle"],["Butterscotch","butterscotch sweet"],["Caramel","caramel cuddle"],["Toffee","toffee sweet"],
["Snuggles","snuggles boy"],["Honeybear","honey bear cuddle"]
],
      "adventurous": [
["Atlas","world explorer"],["Hunter","hunter of adventure"],["Legend","legendary explorer"],["Scout","scout explorer"],["Rover","roving adventurer"],
["Orion","star explorer"],["Pioneer","pioneer explorer"],["Seeker","seeker of fun"],["Travis","trekking traveler"],["Voyage","voyage traveler"],
["Walker","walking adventurer"],["Wilder","wild explorer"],["Wyatt","wyatt wanderer"],["Axel","ax-wielding explorer"],["Baron","baron explorer"],
["Explorer","explorer name"],["Nomad","nomadic wanderer"],["Ranger","ranger explorer"],["Trekker","trekking explorer"],["Advent","advent adventurer"],
["Argus","argus explorer"],["Boone","boone explorer"],["Captain","captain explorer"],["Cobalt","cobalt explorer"],["Convoy","convoy explorer"],
["Cross","cross explorer"],["Drake","drake explorer"],["Everest","everest explorer"],["Frontier","frontier explorer"],["Galleon","galleon explorer"],
["Hiker","hiker explorer"],["Journey","journey traveler"],["Kepler","kepler explorer"],["Mariner","mariner explorer"],["Navigator","navigator explorer"],
["Outlaw","outlaw explorer"],["Pathfinder","pathfinder explorer"],["Pilot","pilot explorer"],["Quest","quest explorer"],["Rambler","rambling explorer"],
["Sailor","sailor explorer"],["Trapper","trapper explorer"],["Wander","wandering soul"],["Wayfarer","wayfarer explorer"],["West","western explorer"],
["Woodsman","woodsman explorer"],["Yonder","yonder explorer"],["Zephyr","zephyr wind"],["Angus","scottish angus"],["Hamish","highland explorer"]
],
      "shy": [
["Asher","gentle asher"],["Beau","gentle beau"],["Eli","gentle eli"],["Graham","gentle graham"],["Hugo","gentle hugo"],
["Kian","gentle kian"],["Landon","gentle landon"],["Miles","gentle miles"],["Noah","gentle noah"],["Owen","gentle owen"],
["Silas","gentle silas"],["Caspian","gentle caspian"],["Felix","gentle felix"],["Jasper","gentle jasper"],["Aaron","gentle aaron"],
["Amos","gentle amos"],["Arthur","gentle arthur"],["Bram","gentle bram"],["Calvin","gentle calvin"],["Cedric","gentle cedric"],
["Clark","gentle clark"],["Cole","gentle cole"],["Conrad","gentle conrad"],["Cort","gentle cort"],["Dean","gentle dean"],
["Denton","gentle denton"],["Duncan","gentle duncan"],["Edward","gentle edward"],["Ellis","gentle ellis"],["Emerson","gentle emerson"],
["Ervin","gentle ervin"],["Ford","gentle ford"],["Francis","gentle francis"],["Glenn","gentle glenn"],["Grant","gentle grant"],
["Heath","gentle heath"],["Ian","gentle ian"],["Isaac","gentle isaac"],["Joel","gentle joel"],["Jude","gentle jude"],
["Kent","gentle kent"],["Leonard","gentle leonard"],["Lewis","gentle lewis"],["Martin","gentle martin"],["Nathan","gentle nathan"],
["Paul","gentle paul"],["Philip","gentle philip"],["Ralph","gentle ralph"],["Reed","gentle reed"],["Roy","gentle roy"]
],
      "affectionate": [
["Cooper","loving golden"],["Buddy","best friend forever"],["Bear","big loving bear"],["Teddy","loving teddy"],["Charlie","charming love"],
["Bailey","loving bailey"],["Milo","milo the loving"],["Oliver","loving oliver"],["Riley","loving riley"],["Tucker","loving tucker"],
["Max","loving max"],["Sam","loving sam"],["Louie","loving louie"],["Henry","loving henry"],["Jackson","loving jackson"],
["Leo","loving lion"],["Milo","sweet milo"],["Ollie","loving ollie"],["Bentley","loving bentley"],["Finn","loving finn"],
["Archie","loving archie"],["Gus","loving gus"],["Hank","loving hank"],["Jasper","loving jasper"],["Loki","loving loki"],
["Dexter","loving dexter"],["Murphy","loving murphy"],["Winston","loving winston"],["Cody","loving cody"],["Dakota","loving dakota"],
["Oakley","loving oakley"],["Ranger","loving ranger"],["Scout","loving scout"],["Theo","loving theo"],["Toby","loving toby"],
["Wally","loving wally"],["Ziggy","loving ziggy"],["Augie","loving augie"],["Benny","loving benny"],["Clyde","loving clyde"],
["Dune","loving dune"],["Harley","loving harley"],["Marley","loving marley"],["Ranger","loving ranger"],["Skipper","loving skipper"],
["Biscuit","loving biscuit"],["Honey","loving honey"],["Butters","loving butters"],["Sunny","loving sunny"],["Angus","loving angus"]
]
    },
    "french_bulldog": {
      "playful": [
["Biscuit","golden playful pup"],["Sunny","sunshine golden boy"],["Marley","bob marley vibes"],["Cooper","friendly cooper"],["Tucker","tuckered from play"],
["Charlie","charming charlie"],["Milo","milo the playful"],["Otis","playful otis"],["Teddy","teddy the playful"],["Bailey","bailey the playful"],
["Riley","riley the playful"],["Henry","henry the playful"],["Oliver","oliver the playful"],["Archie","archie the playful"],["Dexter","dex the playful"],
["Finn","finn the playful"],["Louie","louie the playful"],["Gus","gus the playful"],["Ziggy","ziggy the playful"],["Cody","cody the playful"],
["Toby","toby the playful"],["Rex","rex the playful"],["Benny","benny the playful"],["Jasper","jasper the playful"],["Loki","loki the playful"],
["Bentley","bentley the playful"],["Leo","leo the playful"],["Hank","hank the playful"],["Caramel","caramel-coated pup"],["Tanner","golden tanner"],
["Sandy","sandy the playful"],["Butters","butterscotch boy"],["Amber","amber the playful"],["Honey","honey the playful"],["Blaze","golden blaze"],
["Skipper","skipping pup"],["Augie","august golden"],["Juno","juno the playful"],["Brooks","brookside pup"],["Clyde","clyde the playful"],
["Angus","scottish angus"],["Brio","brio the playful"],["Bounce","bouncy golden"],["Flicker","flickering playful"],["Rolly","rolly polly pup"],
["Dune","dune the playful"],["Wally","wally the playful"],["Tater","tater the playful"],["Nugget","golden nugget"],["Bingo","bingo the playful"]
],
      "energetic": [
["Blaze","fiery golden"],["Dakota","dakota the runner"],["Ranger","ranger energy"],["Trek","trekking golden"],["Chase","chase the retriever"],
["Dash","dash the retriever"],["Canyon","canyon the runner"],["Rio","rio energy"],["Sprint","sprinting retriever"],["Maverick","maverick energy"],
["Bolt","bolt speed"],["Flash","flash the retriever"],["Storm","stormy retriever"],["Comet","comet the runner"],["Rocket","rocket energy"],
["Arrow","arrow the retriever"],["Hawk","hawk-eyed hunter"],["Strider","long strider"],["Gallop","galloping golden"],["River","river runner"],
["Rush","rushing energy"],["Titan","titanic golden"],["Trekker","trekking retriever"],["Phoenix","phoenix rising"],["Rebel","rebel runner"],
["Jet","jet speed"],["Thor","thunder energy"],["Brisk","brisk pace"],["Dune","dune runner"],["Clyde","clyde energy"],
["Boomer","boomer energy"],["Bandit","bandit runner"],["Vortex","vortex energy"],["Cyclone","cyclone energy"],["Dynamo","dynamo power"],
["Spark","spark energy"],["Surge","surge energy"],["Fury","fury energy"],["Flash","flash speed"],["Stride","strider energy"],
["Charger","charger energy"],["Wild","wild energy"],["Zest","zesty runner"],["Comet","comet speed"],["Maverick","maverick speed"],
["Marathon","marathon runner"],["Cascade","cascade energy"],["Glen","glen runner"],["Boulder","boulder strength"],["Summit","summit reacher"],
["Pioneer","pioneer runner"],["Viking","viking runner"],["Mariner","mariner explorer"],["Skipper","skipper retriever"]
],
      "cuddly": [
["Bear","big cuddly bear"],["Teddy","teddy bear cuddle"],["Milo","sweet cuddle bug"],["Ollie","cuddly ollie"],["Charlie","charming cuddle"],
["Sammy","sweet cuddles"],["Benny","benny cuddles"],["Cubby","cubby cuddle"],["Muffin","sweet muffin"],["Pebble","pebble cuddle"],
["Sunny","sunny cuddles"],["Lucky","lucky cuddle"],["Leo","lion cuddle"],["Coby","coby cuddles"],["Archie","archie cuddle"],
["Cooper","cooper cuddles"],["Gus","gus cuddles"],["Louie","louie cuddles"],["Theo","theo cuddles"],["Woody","woody cuddles"],
["Bean","bean cuddle"],["Biscuit","biscuit cuddle"],["Bonbon","sweet bonbon"],["Bubba","bubba cuddles"],["Clover","clover cuddle"],
["Dino","dino cuddles"],["Dotty","dotty cuddles"],["Fluff","fluffy cuddle"],["Fudge","fudge sweet"],["Honey","honey sweet"],
["Jaxie","jaxie cuddles"],["Juno","juno cuddles"],["Mochi","sweet mochi"],["Nibs","nibs sweet"],["Nutty","nutty sweet"],
["Peanut","peanut sweet"],["Puff","puffy cuddle"],["Roo","roo cuddle"],["Snoopy","snoopy cuddles"],["Sprout","sprout cuddle"],
["Sugar","sugar sweet"],["Tiny","tiny cuddle"],["Winnie","winnie cuddles"],["Yogi","yogi cuddles"],["Babe","babe cuddles"],
["Cuddle","cuddle bug"],["Dimple","dimple cuddle"],["Butterscotch","butterscotch sweet"],["Caramel","caramel cuddle"],["Toffee","toffee sweet"],
["Snuggles","snuggles boy"],["Honeybear","honey bear cuddle"]
],
      "adventurous": [
["Atlas","world explorer"],["Hunter","hunter of adventure"],["Legend","legendary explorer"],["Scout","scout explorer"],["Rover","roving adventurer"],
["Orion","star explorer"],["Pioneer","pioneer explorer"],["Seeker","seeker of fun"],["Travis","trekking traveler"],["Voyage","voyage traveler"],
["Walker","walking adventurer"],["Wilder","wild explorer"],["Wyatt","wyatt wanderer"],["Axel","ax-wielding explorer"],["Baron","baron explorer"],
["Explorer","explorer name"],["Nomad","nomadic wanderer"],["Ranger","ranger explorer"],["Trekker","trekking explorer"],["Advent","advent adventurer"],
["Argus","argus explorer"],["Boone","boone explorer"],["Captain","captain explorer"],["Cobalt","cobalt explorer"],["Convoy","convoy explorer"],
["Cross","cross explorer"],["Drake","drake explorer"],["Everest","everest explorer"],["Frontier","frontier explorer"],["Galleon","galleon explorer"],
["Hiker","hiker explorer"],["Journey","journey traveler"],["Kepler","kepler explorer"],["Mariner","mariner explorer"],["Navigator","navigator explorer"],
["Outlaw","outlaw explorer"],["Pathfinder","pathfinder explorer"],["Pilot","pilot explorer"],["Quest","quest explorer"],["Rambler","rambling explorer"],
["Sailor","sailor explorer"],["Trapper","trapper explorer"],["Wander","wandering soul"],["Wayfarer","wayfarer explorer"],["West","western explorer"],
["Woodsman","woodsman explorer"],["Yonder","yonder explorer"],["Zephyr","zephyr wind"],["Angus","scottish angus"],["Hamish","highland explorer"]
],
      "shy": [
["Asher","gentle asher"],["Beau","gentle beau"],["Eli","gentle eli"],["Graham","gentle graham"],["Hugo","gentle hugo"],
["Kian","gentle kian"],["Landon","gentle landon"],["Miles","gentle miles"],["Noah","gentle noah"],["Owen","gentle owen"],
["Silas","gentle silas"],["Caspian","gentle caspian"],["Felix","gentle felix"],["Jasper","gentle jasper"],["Aaron","gentle aaron"],
["Amos","gentle amos"],["Arthur","gentle arthur"],["Bram","gentle bram"],["Calvin","gentle calvin"],["Cedric","gentle cedric"],
["Clark","gentle clark"],["Cole","gentle cole"],["Conrad","gentle conrad"],["Cort","gentle cort"],["Dean","gentle dean"],
["Denton","gentle denton"],["Duncan","gentle duncan"],["Edward","gentle edward"],["Ellis","gentle ellis"],["Emerson","gentle emerson"],
["Ervin","gentle ervin"],["Ford","gentle ford"],["Francis","gentle francis"],["Glenn","gentle glenn"],["Grant","gentle grant"],
["Heath","gentle heath"],["Ian","gentle ian"],["Isaac","gentle isaac"],["Joel","gentle joel"],["Jude","gentle jude"],
["Kent","gentle kent"],["Leonard","gentle leonard"],["Lewis","gentle lewis"],["Martin","gentle martin"],["Nathan","gentle nathan"],
["Paul","gentle paul"],["Philip","gentle philip"],["Ralph","gentle ralph"],["Reed","gentle reed"],["Roy","gentle roy"]
],
      "affectionate": [
["Cooper","loving golden"],["Buddy","best friend forever"],["Bear","big loving bear"],["Teddy","loving teddy"],["Charlie","charming love"],
["Bailey","loving bailey"],["Milo","milo the loving"],["Oliver","loving oliver"],["Riley","loving riley"],["Tucker","loving tucker"],
["Max","loving max"],["Sam","loving sam"],["Louie","loving louie"],["Henry","loving henry"],["Jackson","loving jackson"],
["Leo","loving lion"],["Milo","sweet milo"],["Ollie","loving ollie"],["Bentley","loving bentley"],["Finn","loving finn"],
["Archie","loving archie"],["Gus","loving gus"],["Hank","loving hank"],["Jasper","loving jasper"],["Loki","loving loki"],
["Dexter","loving dexter"],["Murphy","loving murphy"],["Winston","loving winston"],["Cody","loving cody"],["Dakota","loving dakota"],
["Oakley","loving oakley"],["Ranger","loving ranger"],["Scout","loving scout"],["Theo","loving theo"],["Toby","loving toby"],
["Wally","loving wally"],["Ziggy","loving ziggy"],["Augie","loving augie"],["Benny","loving benny"],["Clyde","loving clyde"],
["Dune","loving dune"],["Harley","loving harley"],["Marley","loving marley"],["Ranger","loving ranger"],["Skipper","loving skipper"],
["Biscuit","loving biscuit"],["Honey","loving honey"],["Butters","loving butters"],["Sunny","loving sunny"],["Angus","loving angus"]
]
    },
    "chihuahua": {
      "playful": [
["Biscuit","golden playful pup"],["Sunny","sunshine golden boy"],["Marley","bob marley vibes"],["Cooper","friendly cooper"],["Tucker","tuckered from play"],
["Charlie","charming charlie"],["Milo","milo the playful"],["Otis","playful otis"],["Teddy","teddy the playful"],["Bailey","bailey the playful"],
["Riley","riley the playful"],["Henry","henry the playful"],["Oliver","oliver the playful"],["Archie","archie the playful"],["Dexter","dex the playful"],
["Finn","finn the playful"],["Louie","louie the playful"],["Gus","gus the playful"],["Ziggy","ziggy the playful"],["Cody","cody the playful"],
["Toby","toby the playful"],["Rex","rex the playful"],["Benny","benny the playful"],["Jasper","jasper the playful"],["Loki","loki the playful"],
["Bentley","bentley the playful"],["Leo","leo the playful"],["Hank","hank the playful"],["Caramel","caramel-coated pup"],["Tanner","golden tanner"],
["Sandy","sandy the playful"],["Butters","butterscotch boy"],["Amber","amber the playful"],["Honey","honey the playful"],["Blaze","golden blaze"],
["Skipper","skipping pup"],["Augie","august golden"],["Juno","juno the playful"],["Brooks","brookside pup"],["Clyde","clyde the playful"],
["Angus","scottish angus"],["Brio","brio the playful"],["Bounce","bouncy golden"],["Flicker","flickering playful"],["Rolly","rolly polly pup"],
["Dune","dune the playful"],["Wally","wally the playful"],["Tater","tater the playful"],["Nugget","golden nugget"],["Bingo","bingo the playful"]
],
      "energetic": [
["Blaze","fiery golden"],["Dakota","dakota the runner"],["Ranger","ranger energy"],["Trek","trekking golden"],["Chase","chase the retriever"],
["Dash","dash the retriever"],["Canyon","canyon the runner"],["Rio","rio energy"],["Sprint","sprinting retriever"],["Maverick","maverick energy"],
["Bolt","bolt speed"],["Flash","flash the retriever"],["Storm","stormy retriever"],["Comet","comet the runner"],["Rocket","rocket energy"],
["Arrow","arrow the retriever"],["Hawk","hawk-eyed hunter"],["Strider","long strider"],["Gallop","galloping golden"],["River","river runner"],
["Rush","rushing energy"],["Titan","titanic golden"],["Trekker","trekking retriever"],["Phoenix","phoenix rising"],["Rebel","rebel runner"],
["Jet","jet speed"],["Thor","thunder energy"],["Brisk","brisk pace"],["Dune","dune runner"],["Clyde","clyde energy"],
["Boomer","boomer energy"],["Bandit","bandit runner"],["Vortex","vortex energy"],["Cyclone","cyclone energy"],["Dynamo","dynamo power"],
["Spark","spark energy"],["Surge","surge energy"],["Fury","fury energy"],["Flash","flash speed"],["Stride","strider energy"],
["Charger","charger energy"],["Wild","wild energy"],["Zest","zesty runner"],["Comet","comet speed"],["Maverick","maverick speed"],
["Marathon","marathon runner"],["Cascade","cascade energy"],["Glen","glen runner"],["Boulder","boulder strength"],["Summit","summit reacher"],
["Pioneer","pioneer runner"],["Viking","viking runner"],["Mariner","mariner explorer"],["Skipper","skipper retriever"]
],
      "cuddly": [
["Bear","big cuddly bear"],["Teddy","teddy bear cuddle"],["Milo","sweet cuddle bug"],["Ollie","cuddly ollie"],["Charlie","charming cuddle"],
["Sammy","sweet cuddles"],["Benny","benny cuddles"],["Cubby","cubby cuddle"],["Muffin","sweet muffin"],["Pebble","pebble cuddle"],
["Sunny","sunny cuddles"],["Lucky","lucky cuddle"],["Leo","lion cuddle"],["Coby","coby cuddles"],["Archie","archie cuddle"],
["Cooper","cooper cuddles"],["Gus","gus cuddles"],["Louie","louie cuddles"],["Theo","theo cuddles"],["Woody","woody cuddles"],
["Bean","bean cuddle"],["Biscuit","biscuit cuddle"],["Bonbon","sweet bonbon"],["Bubba","bubba cuddles"],["Clover","clover cuddle"],
["Dino","dino cuddles"],["Dotty","dotty cuddles"],["Fluff","fluffy cuddle"],["Fudge","fudge sweet"],["Honey","honey sweet"],
["Jaxie","jaxie cuddles"],["Juno","juno cuddles"],["Mochi","sweet mochi"],["Nibs","nibs sweet"],["Nutty","nutty sweet"],
["Peanut","peanut sweet"],["Puff","puffy cuddle"],["Roo","roo cuddle"],["Snoopy","snoopy cuddles"],["Sprout","sprout cuddle"],
["Sugar","sugar sweet"],["Tiny","tiny cuddle"],["Winnie","winnie cuddles"],["Yogi","yogi cuddles"],["Babe","babe cuddles"],
["Cuddle","cuddle bug"],["Dimple","dimple cuddle"],["Butterscotch","butterscotch sweet"],["Caramel","caramel cuddle"],["Toffee","toffee sweet"],
["Snuggles","snuggles boy"],["Honeybear","honey bear cuddle"]
],
      "adventurous": [
["Atlas","world explorer"],["Hunter","hunter of adventure"],["Legend","legendary explorer"],["Scout","scout explorer"],["Rover","roving adventurer"],
["Orion","star explorer"],["Pioneer","pioneer explorer"],["Seeker","seeker of fun"],["Travis","trekking traveler"],["Voyage","voyage traveler"],
["Walker","walking adventurer"],["Wilder","wild explorer"],["Wyatt","wyatt wanderer"],["Axel","ax-wielding explorer"],["Baron","baron explorer"],
["Explorer","explorer name"],["Nomad","nomadic wanderer"],["Ranger","ranger explorer"],["Trekker","trekking explorer"],["Advent","advent adventurer"],
["Argus","argus explorer"],["Boone","boone explorer"],["Captain","captain explorer"],["Cobalt","cobalt explorer"],["Convoy","convoy explorer"],
["Cross","cross explorer"],["Drake","drake explorer"],["Everest","everest explorer"],["Frontier","frontier explorer"],["Galleon","galleon explorer"],
["Hiker","hiker explorer"],["Journey","journey traveler"],["Kepler","kepler explorer"],["Mariner","mariner explorer"],["Navigator","navigator explorer"],
["Outlaw","outlaw explorer"],["Pathfinder","pathfinder explorer"],["Pilot","pilot explorer"],["Quest","quest explorer"],["Rambler","rambling explorer"],
["Sailor","sailor explorer"],["Trapper","trapper explorer"],["Wander","wandering soul"],["Wayfarer","wayfarer explorer"],["West","western explorer"],
["Woodsman","woodsman explorer"],["Yonder","yonder explorer"],["Zephyr","zephyr wind"],["Angus","scottish angus"],["Hamish","highland explorer"]
],
      "shy": [
["Asher","gentle asher"],["Beau","gentle beau"],["Eli","gentle eli"],["Graham","gentle graham"],["Hugo","gentle hugo"],
["Kian","gentle kian"],["Landon","gentle landon"],["Miles","gentle miles"],["Noah","gentle noah"],["Owen","gentle owen"],
["Silas","gentle silas"],["Caspian","gentle caspian"],["Felix","gentle felix"],["Jasper","gentle jasper"],["Aaron","gentle aaron"],
["Amos","gentle amos"],["Arthur","gentle arthur"],["Bram","gentle bram"],["Calvin","gentle calvin"],["Cedric","gentle cedric"],
["Clark","gentle clark"],["Cole","gentle cole"],["Conrad","gentle conrad"],["Cort","gentle cort"],["Dean","gentle dean"],
["Denton","gentle denton"],["Duncan","gentle duncan"],["Edward","gentle edward"],["Ellis","gentle ellis"],["Emerson","gentle emerson"],
["Ervin","gentle ervin"],["Ford","gentle ford"],["Francis","gentle francis"],["Glenn","gentle glenn"],["Grant","gentle grant"],
["Heath","gentle heath"],["Ian","gentle ian"],["Isaac","gentle isaac"],["Joel","gentle joel"],["Jude","gentle jude"],
["Kent","gentle kent"],["Leonard","gentle leonard"],["Lewis","gentle lewis"],["Martin","gentle martin"],["Nathan","gentle nathan"],
["Paul","gentle paul"],["Philip","gentle philip"],["Ralph","gentle ralph"],["Reed","gentle reed"],["Roy","gentle roy"]
],
      "affectionate": [
["Cooper","loving golden"],["Buddy","best friend forever"],["Bear","big loving bear"],["Teddy","loving teddy"],["Charlie","charming love"],
["Bailey","loving bailey"],["Milo","milo the loving"],["Oliver","loving oliver"],["Riley","loving riley"],["Tucker","loving tucker"],
["Max","loving max"],["Sam","loving sam"],["Louie","loving louie"],["Henry","loving henry"],["Jackson","loving jackson"],
["Leo","loving lion"],["Milo","sweet milo"],["Ollie","loving ollie"],["Bentley","loving bentley"],["Finn","loving finn"],
["Archie","loving archie"],["Gus","loving gus"],["Hank","loving hank"],["Jasper","loving jasper"],["Loki","loving loki"],
["Dexter","loving dexter"],["Murphy","loving murphy"],["Winston","loving winston"],["Cody","loving cody"],["Dakota","loving dakota"],
["Oakley","loving oakley"],["Ranger","loving ranger"],["Scout","loving scout"],["Theo","loving theo"],["Toby","loving toby"],
["Wally","loving wally"],["Ziggy","loving ziggy"],["Augie","loving augie"],["Benny","loving benny"],["Clyde","loving clyde"],
["Dune","loving dune"],["Harley","loving harley"],["Marley","loving marley"],["Ranger","loving ranger"],["Skipper","loving skipper"],
["Biscuit","loving biscuit"],["Honey","loving honey"],["Butters","loving butters"],["Sunny","loving sunny"],["Angus","loving angus"]
]
    },
    "german_shepherd": {
      "playful": [
["Biscuit","golden playful pup"],["Sunny","sunshine golden boy"],["Marley","bob marley vibes"],["Cooper","friendly cooper"],["Tucker","tuckered from play"],
["Charlie","charming charlie"],["Milo","milo the playful"],["Otis","playful otis"],["Teddy","teddy the playful"],["Bailey","bailey the playful"],
["Riley","riley the playful"],["Henry","henry the playful"],["Oliver","oliver the playful"],["Archie","archie the playful"],["Dexter","dex the playful"],
["Finn","finn the playful"],["Louie","louie the playful"],["Gus","gus the playful"],["Ziggy","ziggy the playful"],["Cody","cody the playful"],
["Toby","toby the playful"],["Rex","rex the playful"],["Benny","benny the playful"],["Jasper","jasper the playful"],["Loki","loki the playful"],
["Bentley","bentley the playful"],["Leo","leo the playful"],["Hank","hank the playful"],["Caramel","caramel-coated pup"],["Tanner","golden tanner"],
["Sandy","sandy the playful"],["Butters","butterscotch boy"],["Amber","amber the playful"],["Honey","honey the playful"],["Blaze","golden blaze"],
["Skipper","skipping pup"],["Augie","august golden"],["Juno","juno the playful"],["Brooks","brookside pup"],["Clyde","clyde the playful"],
["Angus","scottish angus"],["Brio","brio the playful"],["Bounce","bouncy golden"],["Flicker","flickering playful"],["Rolly","rolly polly pup"],
["Dune","dune the playful"],["Wally","wally the playful"],["Tater","tater the playful"],["Nugget","golden nugget"],["Bingo","bingo the playful"]
],
      "energetic": [
["Blaze","fiery golden"],["Dakota","dakota the runner"],["Ranger","ranger energy"],["Trek","trekking golden"],["Chase","chase the retriever"],
["Dash","dash the retriever"],["Canyon","canyon the runner"],["Rio","rio energy"],["Sprint","sprinting retriever"],["Maverick","maverick energy"],
["Bolt","bolt speed"],["Flash","flash the retriever"],["Storm","stormy retriever"],["Comet","comet the runner"],["Rocket","rocket energy"],
["Arrow","arrow the retriever"],["Hawk","hawk-eyed hunter"],["Strider","long strider"],["Gallop","galloping golden"],["River","river runner"],
["Rush","rushing energy"],["Titan","titanic golden"],["Trekker","trekking retriever"],["Phoenix","phoenix rising"],["Rebel","rebel runner"],
["Jet","jet speed"],["Thor","thunder energy"],["Brisk","brisk pace"],["Dune","dune runner"],["Clyde","clyde energy"],
["Boomer","boomer energy"],["Bandit","bandit runner"],["Vortex","vortex energy"],["Cyclone","cyclone energy"],["Dynamo","dynamo power"],
["Spark","spark energy"],["Surge","surge energy"],["Fury","fury energy"],["Flash","flash speed"],["Stride","strider energy"],
["Charger","charger energy"],["Wild","wild energy"],["Zest","zesty runner"],["Comet","comet speed"],["Maverick","maverick speed"],
["Marathon","marathon runner"],["Cascade","cascade energy"],["Glen","glen runner"],["Boulder","boulder strength"],["Summit","summit reacher"],
["Pioneer","pioneer runner"],["Viking","viking runner"],["Mariner","mariner explorer"],["Skipper","skipper retriever"]
],
      "cuddly": [
["Bear","big cuddly bear"],["Teddy","teddy bear cuddle"],["Milo","sweet cuddle bug"],["Ollie","cuddly ollie"],["Charlie","charming cuddle"],
["Sammy","sweet cuddles"],["Benny","benny cuddles"],["Cubby","cubby cuddle"],["Muffin","sweet muffin"],["Pebble","pebble cuddle"],
["Sunny","sunny cuddles"],["Lucky","lucky cuddle"],["Leo","lion cuddle"],["Coby","coby cuddles"],["Archie","archie cuddle"],
["Cooper","cooper cuddles"],["Gus","gus cuddles"],["Louie","louie cuddles"],["Theo","theo cuddles"],["Woody","woody cuddles"],
["Bean","bean cuddle"],["Biscuit","biscuit cuddle"],["Bonbon","sweet bonbon"],["Bubba","bubba cuddles"],["Clover","clover cuddle"],
["Dino","dino cuddles"],["Dotty","dotty cuddles"],["Fluff","fluffy cuddle"],["Fudge","fudge sweet"],["Honey","honey sweet"],
["Jaxie","jaxie cuddles"],["Juno","juno cuddles"],["Mochi","sweet mochi"],["Nibs","nibs sweet"],["Nutty","nutty sweet"],
["Peanut","peanut sweet"],["Puff","puffy cuddle"],["Roo","roo cuddle"],["Snoopy","snoopy cuddles"],["Sprout","sprout cuddle"],
["Sugar","sugar sweet"],["Tiny","tiny cuddle"],["Winnie","winnie cuddles"],["Yogi","yogi cuddles"],["Babe","babe cuddles"],
["Cuddle","cuddle bug"],["Dimple","dimple cuddle"],["Butterscotch","butterscotch sweet"],["Caramel","caramel cuddle"],["Toffee","toffee sweet"],
["Snuggles","snuggles boy"],["Honeybear","honey bear cuddle"]
],
      "adventurous": [
["Atlas","world explorer"],["Hunter","hunter of adventure"],["Legend","legendary explorer"],["Scout","scout explorer"],["Rover","roving adventurer"],
["Orion","star explorer"],["Pioneer","pioneer explorer"],["Seeker","seeker of fun"],["Travis","trekking traveler"],["Voyage","voyage traveler"],
["Walker","walking adventurer"],["Wilder","wild explorer"],["Wyatt","wyatt wanderer"],["Axel","ax-wielding explorer"],["Baron","baron explorer"],
["Explorer","explorer name"],["Nomad","nomadic wanderer"],["Ranger","ranger explorer"],["Trekker","trekking explorer"],["Advent","advent adventurer"],
["Argus","argus explorer"],["Boone","boone explorer"],["Captain","captain explorer"],["Cobalt","cobalt explorer"],["Convoy","convoy explorer"],
["Cross","cross explorer"],["Drake","drake explorer"],["Everest","everest explorer"],["Frontier","frontier explorer"],["Galleon","galleon explorer"],
["Hiker","hiker explorer"],["Journey","journey traveler"],["Kepler","kepler explorer"],["Mariner","mariner explorer"],["Navigator","navigator explorer"],
["Outlaw","outlaw explorer"],["Pathfinder","pathfinder explorer"],["Pilot","pilot explorer"],["Quest","quest explorer"],["Rambler","rambling explorer"],
["Sailor","sailor explorer"],["Trapper","trapper explorer"],["Wander","wandering soul"],["Wayfarer","wayfarer explorer"],["West","western explorer"],
["Woodsman","woodsman explorer"],["Yonder","yonder explorer"],["Zephyr","zephyr wind"],["Angus","scottish angus"],["Hamish","highland explorer"]
],
      "shy": [
["Asher","gentle asher"],["Beau","gentle beau"],["Eli","gentle eli"],["Graham","gentle graham"],["Hugo","gentle hugo"],
["Kian","gentle kian"],["Landon","gentle landon"],["Miles","gentle miles"],["Noah","gentle noah"],["Owen","gentle owen"],
["Silas","gentle silas"],["Caspian","gentle caspian"],["Felix","gentle felix"],["Jasper","gentle jasper"],["Aaron","gentle aaron"],
["Amos","gentle amos"],["Arthur","gentle arthur"],["Bram","gentle bram"],["Calvin","gentle calvin"],["Cedric","gentle cedric"],
["Clark","gentle clark"],["Cole","gentle cole"],["Conrad","gentle conrad"],["Cort","gentle cort"],["Dean","gentle dean"],
["Denton","gentle denton"],["Duncan","gentle duncan"],["Edward","gentle edward"],["Ellis","gentle ellis"],["Emerson","gentle emerson"],
["Ervin","gentle ervin"],["Ford","gentle ford"],["Francis","gentle francis"],["Glenn","gentle glenn"],["Grant","gentle grant"],
["Heath","gentle heath"],["Ian","gentle ian"],["Isaac","gentle isaac"],["Joel","gentle joel"],["Jude","gentle jude"],
["Kent","gentle kent"],["Leonard","gentle leonard"],["Lewis","gentle lewis"],["Martin","gentle martin"],["Nathan","gentle nathan"],
["Paul","gentle paul"],["Philip","gentle philip"],["Ralph","gentle ralph"],["Reed","gentle reed"],["Roy","gentle roy"]
],
      "affectionate": [
["Cooper","loving golden"],["Buddy","best friend forever"],["Bear","big loving bear"],["Teddy","loving teddy"],["Charlie","charming love"],
["Bailey","loving bailey"],["Milo","milo the loving"],["Oliver","loving oliver"],["Riley","loving riley"],["Tucker","loving tucker"],
["Max","loving max"],["Sam","loving sam"],["Louie","loving louie"],["Henry","loving henry"],["Jackson","loving jackson"],
["Leo","loving lion"],["Milo","sweet milo"],["Ollie","loving ollie"],["Bentley","loving bentley"],["Finn","loving finn"],
["Archie","loving archie"],["Gus","loving gus"],["Hank","loving hank"],["Jasper","loving jasper"],["Loki","loving loki"],
["Dexter","loving dexter"],["Murphy","loving murphy"],["Winston","loving winston"],["Cody","loving cody"],["Dakota","loving dakota"],
["Oakley","loving oakley"],["Ranger","loving ranger"],["Scout","loving scout"],["Theo","loving theo"],["Toby","loving toby"],
["Wally","loving wally"],["Ziggy","loving ziggy"],["Augie","loving augie"],["Benny","loving benny"],["Clyde","loving clyde"],
["Dune","loving dune"],["Harley","loving harley"],["Marley","loving marley"],["Ranger","loving ranger"],["Skipper","loving skipper"],
["Biscuit","loving biscuit"],["Honey","loving honey"],["Butters","loving butters"],["Sunny","loving sunny"],["Angus","loving angus"]
]
    }
  }
};
